<div class="box">
    <div class="box-content">
        <h1>Request a catalog</h1>

        <img src="<?php echo Mage::getBaseUrl('media') . 'wysiwyg/RequestCatalog.jpg'?>" style="width:100%;"/>

    </div>
        <form id="requestCatalogForm" action="<?php echo $this->getRequestCatalogSave() ?>" method="post">
        <div class="fieldset">
            <h2 class="legend">Contact Information</h2>
            <p class="required">* Required Fields</p>
            <ul class="form-list">
                <li>
                    <label for="first_name" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
                    <div class="input-box">
                        <input type="text" name="first_name" id="first_name" value="" class="input-text required-entry" />
                    </div>
                </li>
                <li>
                    <label for="last_name" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
                    <div class="input-box">
                        <input type="text" name="last_name" id="last_name" value="" class="input-text required-entry" />
                    </div>
                </li>
                <li>
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email" value="" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="future_catalogs" title="" value="1" id="future_catalogs" class="checkbox" />
                    </div>
                    <label for="future_catalogs"><?php echo $this->__('Receive future catalogs') ?></label>
                </li>
            </ul>
        </div>
        <div class="actions">
            <button type="submit" name="submit" title="" class="button"><span><span>Submit</span></span></button>
        </div>
    </form>

    <table>
        <thead>
            <th style="padding-right: 10px;font-weight: bold">ID</th>
            <th style="padding-right: 10px;font-weight: bold">First Name</th>
            <th style="padding-right: 10px;font-weight: bold">Last Name</th>
            <th style="padding-right: 10px;font-weight: bold">Email</th>
        </thead>
        <?php
            $collection = $this->getRequestCatalogCollection();

            foreach ($collection as $item) {
                echo "<tr>";
                echo "<td>" . $item->getId() . "</td>";
                echo "<td>" . $item->getFirstName() . "</td>";
                echo "<td>" . $item->getLastName() . "</td>";
                echo "<td>" . $item->getEmail() . "</td>";
                echo "</tr>";
            }
        ?>
    </table>
</div>

<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('requestCatalogForm');
    //]]>
</script>