<?php
    $shippingArrangement = $this->getShippingArrangement();
    if($shippingArrangement){
?>
        <style type="text/css">
            .order-info-box .box-title{
                width: 190px;
            }
        </style>
    <div class="col-set order-info-box">
        <div class="col">

            <div class="box">

                <div class="box-title">

                    <h2><?php echo $this->__('Shipping Arrangement') ?></h2>
                </div>
                <div class="box-content">

                    <?php echo $shippingArrangement ?>

                </div>
            </div>
        </div>
    </div>
<?php } ?>