<?php $_order = $this->getOrder() ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Shipping Arrangement Details') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td style="width:30%" class="label"><strong>
                        <?php echo Mage::helper('sales')->__('Shipping Arrangement') ?></strong></td>
                    <td class="value"><?php echo $this->getOrder()->getShippingArrangement(); ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>